[~] Last try

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,5 +1,4 @@
 name: chocolatine
-
 on:
   push:
     branches-ignore:
@@ -7,31 +6,25 @@ on:
   pull_request:
     branches-ignore:
       - 'ga-ignore-*'
-
 env:
   MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-LIL-2-1-chocolatine-clement.bouret.git"
   EXECUTABLE: "chocolatine"
-
 jobs:
   is_repo_a_mirror:
     runs-on: ubuntu-latest
-    outputs:
-      is_mirror: ${{ steps.check_mirror.outputs.is_mirror }}
+    if : github.repository != 'EpitechPromo2028/B-DOP-200-LIL-2-1-chocolatine-clement.bouret.git'
     steps:
       - name: Check if repo is a mirror
-        id: check_mirror
         run: |
-          echo "Comparing ${{ github.repository }} with expected non-mirror repository information"
-          if [[ ! "${{ env.MIRROR_URL }}" == "${{ github.repository }}" ]]; then
-            echo "::set-output name=is_mirror::false"
+          if [[ "${GITHUB_REPOSITORY}" == "${MIRROR_URL}" ]]; then
+            echo "Error: This repository is a mirror"
+            exit 1
           else
-            echo "::set-output name=is_mirror::true"
+            echo "This repository is not a mirror"
           fi
-
   check_coding_style:
     runs-on: ubuntu-latest
     needs: is_repo_a_mirror
-    if: ${{ needs.is_repo_a_mirror.outputs.is_mirror == 'false' }}
     container:
       image: "ghcr.io/epitech/coding-style-checker:latest"
       options: --privileged
@@ -54,7 +47,6 @@ jobs:
           if [ $(wc -l < /tmp/coding-style-reports.log) -gt 0 ]; then
             exit 1
           fi
-
   build:
     runs-on: ubuntu-latest
     needs: [check_coding_style, is_repo_a_mirror]
@@ -66,7 +58,6 @@ jobs:
         uses: actions/checkout@v4
       - name: Program Compilation
         run: make
-
   test:
     runs-on: ubuntu-latest
     needs: build
@@ -79,7 +70,6 @@ jobs:
       - name: Run tests
         run: make tests_run
         timeout-minutes: 2
-
   deploy:
     runs-on: ubuntu-latest
     needs: test
